services:
  - type: web
    name: bookings-backend
    env: go
    plan: starter
    buildCommand: go build -o main ./backend-deployment/cmd/web
    startCommand: ./main
    envVars:
      - key: GO_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-app.netlify.app
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: bookings-db
    databaseName: bookings
    user: bookings_user
    plan: starter
    ipAllowList: [] 